# Generated by Django 4.1.3 on 2022-11-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod1', '0003_dataget'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataget',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
