# Generated by Django 4.1.3 on 2022-11-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('bennett_email', models.CharField(max_length=255)),
            ],
        ),
    ]
